(*
    Lexer rules are ALL CAPS
    Parser rules are lowercase

    structs are not included in this grammar for now.
*)
program
    = { function_definition };

function_definition
    = "fn", IDENTIFIER, "(", [ function_params ], ")", [ "->", type ], block;

function_params
    = function_param, { ",", function_param };

function_param
    = [ "mut" ], IDENTIFIER, ":", type;

type
    = "int"
    | "float"
    | "bool"
    | "str"
    | "vec", "<", type, ">"
    | IDENTIFIER;

block
    = "{", { statement }, "}";

statement
    = let_binding
    | assignment_statement
    | if_statement
    | while_statement
    | for_statement
    | return_statement
    | break_statement
    | continue_statement
    | block
    | expression, ";";

let_binding
    = "let", [ "mut" ], IDENTIFIER, [ ":", type ], "=", expression, ";";

assignment_statement
    = assignable, ( "="
    | compound_assignment_op ), expression, ";";

(* To fix. This doesn't catch multiple indexes and nested structs *)
assignable
    = IDENTIFIER
    | IDENTIFIER, "[", expression, "]";

compound_assignment_op
    = "+="
    | "-="
    | "*="
    | "/="
    | "%=";

if_statement
    = "if", expression, block, { "else", "if", expression, block }, [ "else", block ];

while_statement
    = "while", expression, block;

for_statement
    = "for", [ "mut" ], IDENTIFIER, "in", range, block;

range
    = range_bound, "..", [ "=" ], range_bound, [ "..", range_bound ];

range_bound
    = IDENTIFIER
    | literal
    | "(", expression, ")";

return_statement
    = "return", [ expression ], ";";

break_statement
    = "break", ";";

continue_statement
    = "continue", ";";

(* Keywords are excluded from identifiers *)
IDENTIFIER
    = LETTER, { LETTER
    | DIGIT
    | "_" };

LETTER
    = ? [a-zA-Z] ?;

STRING
    = '"', { STRING_CHAR
    | ESCAPE_SEQUENCE }, '"';

(* Change if swap to unicode *)
STRING_CHAR
    = ? any ASCII character except '"' and '\' and NEWLINE ?;

ESCAPE_SEQUENCE
    = "\\", ( '"'
    | "\\"
    | "n"
    | "t"
    | "r"
    | "x", HEX_DIGIT, HEX_DIGIT );

HEX_DIGIT
    = DIGIT
    | ? [a-fA-F] ?;

INTEGER
    = DIGIT_NON_ZERO, { DIGIT
    | ( "_", DIGIT ) }
    | "0";

FLOAT
    = ( DIGIT_NON_ZERO, { DIGIT
    | ( "_", DIGIT ) }
    | "0" ), ".", DIGIT, { DIGIT
    | ( "_", DIGIT ) };

BOOL
    = "true"
    | "false";

DIGIT
    = DIGIT_NON_ZERO
    | "0";

DIGIT_NON_ZERO
    = "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9";

literal
    = INTEGER
    | FLOAT
    | STRING
    | BOOL
    | vec_literal;

vec_literal
    = "[", [ vec_elements ], "]";

vec_elements
    = expression, { ",", expression }, [ "," ];

function_call
    = IDENTIFIER, "(", [ function_arguments ], ")";

function_arguments
    = expression, { ",", expression };

unary_operator
    = "-"
    | "!"
    | "@";

(* Compound assignment is not here, as it's only allowed in assignment statements *)
binary_operator
    = "+"
    | "-"
    | "*"
    | "/"
    | "%"
    | "!="
    | "=="
    | "<"
    | ">"
    | "<="
    | ">="
    | "and"
    | "or"
    | "?"
    | ":>"
    | "><"
    | "in";

(* Whole thing needs change *)
(* expression
    = literal
    | IDENTIFIER
    | function_call
    | unary_operator, expression
    | expression, binary_operator, expression
    | if_expression
    | expression, "[", expression, "]"
    | "(", expression, ")"; *)
expression
    = ;