(*
    Lexer rules are ALL CAPS
    Parser rules are lowercase

    structs are not included in this grammar for now.
*)
program
    = { function_definition };

function_definition
    = "fn", IDENTIFIER, "(", function_params, ")", [ "->", type ], block;

function_params
    = [ function_param, { ",", function_param } ];

function_param
    = [ "mut" ], IDENTIFIER, ":", type;

type
    = "int"
    | "float"
    | "bool"
    | "str"
    | "[", type, "]";

block
    = "{", { statement }, "}";

statement
    = let_binding, ";"
    | assignment_statement, ";"
    | return_statement, ";"
    | break_statement, ";"
    | continue_statement, ";"
    | function_call, ";"
    | block
    | if_statement
    | while_loop
    | for_loop;

let_binding
    = "let", [ "mut" ], IDENTIFIER, [ ":", type ], "=", ( if_expression | expression );

assignment_statement
    = lvalue, ( "=" | compound_assignment_op ), ( if_expression | expression );

if_expression
    = "if", expression, "{", expression, "}", "else", "{", expression, "}";

lvalue
    = IDENTIFIER, { "[", expression, "]" };

compound_assignment_op
    = "+="
    | "-="
    | "*="
    | "/="
    | "%=";

if_statement
    = "if", expression, block, { "else", "if", expression, block }, [ "else", block ];

while_loop
    = "while", expression, block;

for_loop
    = "for", [ "mut" ], IDENTIFIER, "in", range, block;

range
    = range_bound, "..", [ "=" ], range_bound, [ "..", range_bound ];

range_bound
    = identifier_or_call
    | literal
    | "(", expression, ")";

return_statement
    = "return", [ expression ], ";";

break_statement
    = "break", ";";

continue_statement
    = "continue", ";";

(* Keywords are excluded from identifiers *)
IDENTIFIER
    = LETTER, { LETTER | DIGIT | "_" };

LETTER
    = ? [a-zA-Z] ?;

STRING
    = '"', { STRING_CHAR | ESCAPE_SEQUENCE }, '"';

(* Change if swap to unicode *)
STRING_CHAR
    = ? any ASCII character except '"' and '\' and NEWLINE ?;

ESCAPE_SEQUENCE
    = "\\", ( '"'
    | "\\"
    | "n"
    | "t"
    | "r"
    | "x", HEX_DIGIT, HEX_DIGIT );

HEX_DIGIT
    = DIGIT
    | ? [a-fA-F] ?;

INTEGER
    = DIGIT, { [ "_" ], DIGIT };

FLOAT
    = DIGIT, { [ "_" ], DIGIT }, ".", [ DIGIT, { [ "_" ], DIGIT } ];

BOOL
    = "true"
    | "false";

DIGIT
    = DIGIT_NON_ZERO
    | "0";

DIGIT_NON_ZERO
    = "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9";

literal
    = INTEGER
    | FLOAT
    | STRING
    | BOOL
    | vec_literal;

vec_literal
    = "[", vec_elements, "]";

vec_elements
    = [ expression, { ",", expression }, [ "," ] ];

function_call
    = IDENTIFIER, "(", function_arguments, ")";

function_arguments
    = [ expression, { ",", expression } ];

expression
    = disjunction, { ( "?" | ":>" ), disjunction };

disjunction
    = conjunction, { "or", conjunction };

conjunction
    = relation_term, { "and", relation_term };

relation_operator
    = ">="
    | ">"
    | "<="
    | "<"
    | "=="
    | "!=";

relation_term
    = in_application, { relation_operator, in_application };

in_application
    = intersection_application, { "in", intersection_application };

intersection_application
    = additive_term, { "><", additive_term };

additive_term
    = multiplicative_term, { ( "+" | "-" ), multiplicative_term };

multiplicative_term
    = unary_application, { ( "*" | "/" ), unary_application };

unary_application
    = [ "-" | "!" | "@" ], index_application;

index_application
    = term, { "[", expression, "]" };

term
    = literal
    | identifier_or_call
    | "(", expression, ")";

identifier_or_call
    = IDENTIFIER, [ "(", function_arguments, ")" ];
